name: Publish Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build-and-publish:
    name: Build and publish Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Registry
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matthewfeickert/fastjet
        dockerfile: Dockerfile
        tags: latest,fastjet3.3.3,fastjet3.3.3-python3.7
    - name: Build and Publish to Registry with Release Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matthewfeickert/fastjet
        dockerfile: Dockerfile
        tags: latest,latest-stable,fastjet3.3.3,fastjet3.3.3-python3.7
        tag_with_ref: true
